Imported KivyMD
vanityx/SELF_CREATE_2.0 pull request #6
Opened 2020-12-18 22:21 UTC by vanityx

- Created a basic Navigation Drawer
- Deleted redundant files

2020-12-18 22:49 UTC, vanityx commented
https://user-images.githubusercontent.com/46442570/102668227-4c351300-4183-11eb-94c5-0771abe408a1.mp4

2020-12-18 23:49 UTC, vanityx commented
https://user-images.githubusercontent.com/46442570/102673353-b651b600-418b-11eb-998d-2945aa5d556a.mp4

2020-12-20 21:59 UTC, almeister commented on source/main.py
>          nose_colour_num_pos = 14
It might be more clear to store skin colour and nose type on the GameLayout object.  Then you can build the string below without indexing the current skin colour and nose type.  Try something like this.

(constructor)
self.skin_colour = 1
self.nose_type = 1

(change_base) - using format strings.
self.ids.base_img.source = f“../assets/base{value}.png”
self.ids.nose_img.source = f”../assets/nose{self.nose_type}c{value}.png”
self.skin_colour = value

2020-12-20 21:59 UTC, almeister commented on source/main.py
>          curr_skin = self.ids.base_img.source[14]
As with change_base, do something like this instead.

self.ids.nose_img.source = f”../assets/nose{value}c{self.skin_colour}.png”
self.nose_type = value

2020-12-20 21:59 UTC, almeister commented on source/main.py
> +        self.ids.lips_img.source = '../assets/lips' + value + '.png'
Use format strings as I mentioned above.

2020-12-20 22:01 UTC, almeister requested changes
Looks good Sasha.  KivyMD looks great.  You might recognise Material UI (the standard it is based on) from various apps like gmail, Facebook and WhatsApp.  This will be good experience for job applications.

I’m reviewing this on my phone so I’m only imagining what it looks like.  I’m guessing the drawer is empty when the app initialises.  I’m sure you can figure out how to set a default drawer (on startup) if that is what you prefer?

2020-12-20 22:03 UTC, almeister commented
Another thought for you... is there a clever way to refactor or reuse some of the duplicated kv file declarations?

2020-12-29 22:24 UTC, vanityx commented
Uploading NavDrawer_Issues.mp4…

2021-01-10 15:02 UTC, merged